### ISSUE TITLE
New Alarm, Crash if selecting a past date then repeat option.

### ISSUE THREAD

**Issue by sixwheeledbeast** [community-ssu/clock-ui#10]
Save button can be pressed if time is in the past after changing repeat option.

To reproduce:- Set Date to a day in the past, Change the repeat option to a day.
Then switch repeat back to Never, the Save button is now clickible causing a crash.

**Comment by freemangordon** [comment]
Cannot recreate after latest code changes

**Comment by sixwheeledbeast** [comment]
I can reproduce this on 0cssu6 with the instructions above.

**Comment by freemangordon** [comment]
Please test with cssu7, it should have all the issues fixed, besides https://github.com/community-ssu/clock-ui/issues/2
